Vagrant.configure("2") do |config|

  # Definindo a imagem que esta sendo utilizada
  config.vm.box = "centos/7"

  # Configurações de NETWORK
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Configuração de script
  config.vm.provision "shell", path: "provision.sh"

end
